name: flutter_insta_clone
description: A new Flutter project.

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  font_awesome_flutter: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/insta_logo.png

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

    - family: Aveny
      fonts:
        - asset: assets/fonts/AvenyTRegular.otf
          style: normal
        - asset: assets/fonts/AvenyTMedium.otf
          style: italic